[package]
name = "rust-tetris"
version = "0.1.0"
authors = ["y-tsuzaki <y-tsuzaki@macloud.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.14"
termion = "1.5.2"
rand = "0.3.14"
